// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rgi-command/Dashboard.tsx": () => import("../components/mockups/rgi-command/Dashboard.tsx"),
  "./components/mockups/rgi-editorial/Dashboard.tsx": () => import("../components/mockups/rgi-editorial/Dashboard.tsx")
};
