create table if not exists public.articles (
  id integer generated by default as identity primary key,
  headline text not null,
  url text not null unique,
  source_name text not null,
  source_url text,
  author text,
  author_type text,
  platform text not null default 'news',
  is_emerging_signal boolean not null default false,
  is_primary_signal boolean not null default false,
  relevancy_score real not null default 0,
  authenticity_score real default 5,
  viewpoint text,
  topic_tags text[] not null default '{}',
  teaser_summary text,
  published_at timestamptz,
  scraped_at timestamptz not null default now(),
  content text,
  status text not null default 'pending',
  discipline_alignment text
);

create index if not exists articles_scraped_at_idx on public.articles (scraped_at desc);
create index if not exists articles_status_idx on public.articles (status);
create index if not exists articles_relevancy_score_idx on public.articles (relevancy_score desc);

create table if not exists public.digest_articles (
  id integer generated by default as identity primary key,
  article_type text not null default 'topic_article',
  headline text not null,
  body text not null,
  executive_summary text[] not null default '{}',
  rgi_take text not null default '',
  key_takeaways text[] not null default '{}',
  implifications_for_leaders text[] not null default '{}',
  what_most_are_missing text,
  mechanism text[] not null default '{}',
  constraints_and_risks text[] not null default '{}',
  what_changed_since_yesterday text[] not null default '{}',
  what_to_watch text[] not null default '{}',
  summary_takeaways text[] not null default '{}',
  topic_tags text[] not null default '{}',
  source_article_ids integer[] not null default '{}',
  relevancy_score real,
  status text not null default 'pending_review',
  editor_notes text,
  published_at timestamptz,
  discipline text,
  newsletter_sent_at timestamptz,
  newsletter_sent_count integer default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists digest_articles_created_at_idx on public.digest_articles (created_at desc);
create index if not exists digest_articles_status_idx on public.digest_articles (status);
create index if not exists digest_articles_article_type_idx on public.digest_articles (article_type);

create table if not exists public.settings (
  id integer generated by default as identity primary key,
  relevancy_threshold real not null default 7.0,
  scrape_interval_hours integer not null default 24,
  scrape_time_utc text not null default '11:00'
);

insert into public.settings (id, relevancy_threshold, scrape_interval_hours, scrape_time_utc)
values (1, 7.0, 24, '11:00')
on conflict (id) do nothing;
